---
# - name: test minimal copy
#   hosts: min_servers
#   remote_user: test
#   gather_facts: false

#   roles:
#   - minimal

- name: test common copy
  hosts: common_servers
  remote_user: test
  gather_facts: true
  become: yes

  vars_files:
    - group_vars/all.yml

  # - minimal
  roles:
    - copy_bash_files
  # - install_files


# - name: test dev copy
#   hosts: dev_servers
#   remote_user: test
#   gather_facts: false

#   roles:
#   - minimal
#   - common
#   - dev


# - name: test desktop copy
#   hosts: desktop_servers
#   remote_user: test
#   gather_facts: false

#   roles:
#   - minimal
#   - common
#   - dev
#   - desktop
