---
# tasks file for install_files/

# ======================== Arch ================================================
- name: install Archlinux_common packages
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop: "{{ Archlinux_common }}"
  when: ansible_facts['os_family'] == "Archlinux" and role == "common"

- name: install Archlinux_dev packages
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop: "{{ Archlinux_dev }}"
  when: ansible_facts['os_family'] == "Archlinux" and role == "dev"

- name: install Archlinux_desktop packages
  become: yes
  pacman:
    name: "{{item}}"
    state: present
  loop: "{{ Archlinux_desktop }}"
  when: ansible_facts['os_family'] == "Archlinux" and role == "desktop"

# # Todo: SETUP => ansible-galaxy install kewlfft.aur
# https://github.com/kewlfft/ansible-aur
# - name: install yay_dev packages
# become: yes
#   aur:
#     name: "{{item}}"
#     state: present
#   loop: "{{ yay_dev }}"
#   when: ansible_facts['os_family'] == "Archlinux" and role == "dev"



# # ======================== Debian ==============================================

- name: install Debian_common packages
  become: yes
  apt:
    name: "{{item}}"
    state: present
  loop: "{{ Debian_common }}"
  when: ansible_facts['os_family'] == "Debian" and role == "common"

- name: install Debian_dev packages
  become: yes
  apt:
    name: "{{item}}"
    state: present
  loop: "{{ Debian_dev }}"
  when: ansible_facts['os_family'] == "Debian" and role == "dev"

- name: install Debian_desktop packages
  become: yes
  apt:
    name: "{{item}}"
    state: present
  loop: "{{ Debian_desktop }}"
  when: ansible_facts['os_family'] == "Debian" and role == "desktop"
