---
# tasks file for minimal
- name: Create dir structure
  file:
    path: "{{ item }}"
    state: directory
  loop: "{{ created_dirs }}"

- name: Copy role files
  copy:
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
  loop: "{{ dotfile_sources | zip( dotfile_destinations) | list }}"

- name: Create last_role.txt file
  copy:
    dest: "{{home_dir}}/.config/dotfiles/bash/meta/data/last_role.txt"
    content: |
      {{role}}

- name: Append line to current bashrc (to source other files)
  lineinfile:
    path: "{{ home_dir }}/.bashrc"
    line: 'source ~/.config/dotfiles/bash/bashrc.sh'
    insertbefore: EOF

- name: Delete ordered_concatenated_files.txt
  file:
    path: "{{home_dir}}/.config/dotfiles/bash/meta/data/ordered_concatenated_files.txt"
    state: absent

- name: Chown the dotfiles directory (needed in case become = yes for when I am installing files too)
  # ansible.builtin.shell: /bin/bash chown -R {{ansible_ssh_user}}:{{ansible_ssh_user}} {{home_dir}}/.config/dotfiles
  file: dest="{{home_dir}}/.config/dotfiles" owner="{{ansible_ssh_user}}" group="{{ansible_ssh_user}}" mode=0755 recurse=yes
