---
# This file is generated and overwritten by generate.sh

Archlinux_common:
  - neovim
  - tree

Archlinux_desktop:
  - xdg-utils
  - mpv
  - dunst
  - polybar
  - ruby-fusuma
  - kitty
  - picom
  - rofi
  - pavucontrol
  - rofi-calc
  - rofi-pass
  - xcape

Archlinux_dev:
  - git
  - fasd
  - ripgrep
  - fzf
  - bat
  - lsd
  - neofetch
  - yay
  - python-pip

yay_dev:
  - bottom
  - teiler-git

Debian_common:
  - neovim
  - tree

Debian_desktop:
  - xdg-utils
  - mpv
  - dunst
  - kitty
  - pavucontrol
  - rofi

Debian_dev:
  - git
  - fasd
  - ripgrep
  - fzf
  - neofetch
  - python3-pip
  - xcape

