#!/bin/bash

#if [ "$1" == "show" ]; then

# show nothing if spotify is running
if [ "$1" == "show" ]; then
    if pgrep -x spotify > /dev/null 2>&1; then
        echo "show" > /home/brendonk/.config/polybar/showArtist.txt
    else
        echo "nope" > /home/brendonk/.config/polybar/showArtist.txt
    fi

else
    echo "nope" > /home/brendonk/.config/polybar/showArtist.txt
fi
